config/routes.rb
GitErDun::Application.routes.draw do
  devise_for :users

  resources :tags

  resources :tasks

  resources :users

  authenticated :user do
    root to: 'users#index'
  end
  
  match '/quick_timer' => "quick_timer#index"

  root :to => 'welcome#index'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation, :remember_me
  has_many :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/quick_timer_controller.rb
class QuickTimerController < ApplicationController
  before_filter :authenticate_user!
  # GET /quick_timer
  # GET /quick_timer.json
  def index    
    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :ok }
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new
    @user = User.all()

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])
    @task.user_id = current_user.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to :controller => :users, :action => :index }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to :controller => :users, :action => :index }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to :controller => :users, :action => :index }
      format.json { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  # GET /users
  # GET /users.json
  def index
    @tasks = Task.where(:user_id => current_user)
    if params[:task_id] then
      @display_task = @tasks.detect{ |item| item.id == Integer(params[:task_id]) if Integer(params[:task_id]) rescue false }
      if (@display_task.deadline <=> Time.now) < 1 then
        @is_overdue = "True"
      else
        @is_overdue = "False"
      end
    end
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if user_signed_in?
    else

    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

    def devise_mapping
       @devise_mapping ||= Devise.mappings[:user]
    end
    
  def after_sign_in_path_for(resource)
    redirect_to user_landings_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/user_landings_helper.rb
module UserLandingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitErDun</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>

  <%= yield(:header) if content_for? :header %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quick_timer/index.html.erb
<% content_for :header do -%>
  <%= stylesheet_link_tag 'user_landing' %>
  <%= javascript_include_tag 'user_landing' %>
  <%= javascript_include_tag 'quick_timer' %>
<% end %>

<div id="container">
    <div class="hidden">
    <div id="sample-modal"><h2 style="font-size:160%; font-weight:bold; margin:10px 0;">Modal Box Content</h2><p>Place your desired modal box content here</p></div>
    </div><!-- end of hidden -->
    <%= render "user_landing/header", :focus => "quick_timer" %>
<div id="content">

      <%= render "user_landing/left_column" %>
    	<div id="mid-col" class="full-col">
			<div class="box">
				<span class="clearFix">&nbsp;</span>     
		        <div class="box-container">
					Clocky stuff will go in here, at some point, hopefully....
				</div>
			</div>
     	</div>
      <span class="clearFix">&nbsp;</span>     
</div>
<div class="push"></div>
</div>
<div id="footer-wrap"></div>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Color</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= tag.name %></td>
    <td><%= tag.color %></td>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tag.name %>
</p>

<p>
  <b>Color:</b>
  <%= @tag.color %>
</p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Deadline" %><br />
    <%= f.datetime_select :deadline %>
  </div>
  <div class="field">
    <%= f.label "Description" %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label "Reminder" %><br />
    <%= f.datetime_select :reminder %>
  </div>
	<div class="field">
		<%= f.label "Tags"%>
		<%= f.text_field :tag_id %>
		</div>
  <div class="actions">
    <%= f.submit %><%= button_to "Cancel", :root %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<% content_for :header do -%>
  <%= stylesheet_link_tag 'user_landing' %>
  <%= javascript_include_tag 'user_landing' %>
<% end %>

<div id="container">
    <div class="hidden">
    <div id="sample-modal"><h2 style="font-size:160%; font-weight:bold; margin:10px 0;">Modal Box Content</h2><p>Place your desired modal box content here</p></div>
    </div><!-- end of hidden -->
    <%= render "user_landing/header" %>
<div id="content">

      <%= render "user_landing/left_column" %>
<div id="mid-col" class="full-col">
	  <div class="box">
		<h4 class="white">Edit Task</h4>
	<div class="box-container">
      <%= render "form" %>
	</div></div>
</div>
      
      <span class="clearFix">&nbsp;</span>     

</div><!-- end of div#content -->
<div class="push"></div>
</div><!-- end of #container -->

<div id="footer-wrap">
	<div id="footer">
        <div id="footer-top">
        	<div class="align-left">
            <h4>Dashboard</h4>
            <p><a href="#">Dasboard Sub 1</a> | <a href="#">Dasboard Sub 2</a> | <a href="#">Dasboard Sub 3</a></p>
        	</div>
            <div class="align-right">
            <h2><a href="#">Cleanity</a></h2>
            </div>
            <span class="clearFix"></span>
        </div><!-- end of div#footer-top -->
        
        <div id="footer-bottom">
        	<p>&copy; 2009 Cleanity. Theme by Onur Oztaskiran of <a href="http://www.monofactor.com">Monofactor</a>, 
            via <a href="http://themeforest.net">Themeforest</a></p>
        </div>
        
	</div>
</div>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Deadline</th>
    <th>Description</th>
    <th>Reminder</th>
    <th>Completed</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tasks.each do |task| %>
  <tr>
    <td><%= task.deadline %></td>
    <td><%= task.description %></td>
    <td><%= task.reminder %></td>
    <td><%= task.completed %></td>
    <td><%= task.user %></td>
    <td><%= link_to 'Show', task %></td>
    <td><%= link_to 'Edit', edit_task_path(task) %></td>
    <td><%= link_to 'Destroy', task, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<% content_for :header do -%>
  <%= stylesheet_link_tag 'user_landing' %>
  <%= javascript_include_tag 'user_landing' %>
<% end %>

<div id="container">
    <div class="hidden">
    <div id="sample-modal"><h2 style="font-size:160%; font-weight:bold; margin:10px 0;">Modal Box Content</h2><p>Place your desired modal box content here</p></div>
    </div><!-- end of hidden -->
    <%= render "user_landing/header" %>
<div id="content">

      <%= render "user_landing/left_column" %>
<div id="mid-col" class="full-col">
	<%= content_tag('div', flash[:notice], :class => 'flash notice') if flash[:notice] %>
      <%= render "form" %>
</div>
      
      <span class="clearFix">&nbsp;</span>     

</div><!-- end of div#content -->
<div class="push"></div>
</div><!-- end of #container -->

<div id="footer-wrap">
	<div id="footer">
        <div id="footer-top">
        	<div class="align-left">
            <h4>Dashboard</h4>
            <p><a href="#">Dasboard Sub 1</a> | <a href="#">Dasboard Sub 2</a> | <a href="#">Dasboard Sub 3</a></p>
        	</div>
            <div class="align-right">
            <h2><a href="#">Cleanity</a></h2>
            </div>
            <span class="clearFix"></span>
        </div><!-- end of div#footer-top -->
        
        <div id="footer-bottom">
        	<p>&copy; 2009 Cleanity. Theme by Onur Oztaskiran of <a href="http://www.monofactor.com">Monofactor</a>, 
            via <a href="http://themeforest.net">Themeforest</a></p>
        </div>
        
	</div>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Deadline:</b>
  <%= @task.deadline %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Reminder:</b>
  <%= @task.reminder %>
</p>

<p>
  <b>Completed:</b>
  <%= @task.completed %>
</p>

<p>
  <b>User:</b>
  <%= @task.user %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/user_landing/_calendar_widget.html.erb
<div id="calendar-container">
	<h5>Calendar</h5>
	<div id="calendar"></div>
	<div class="inner-nav">
    <div class="align-left"><a href="#"><span>+ add event</span></a></div>
    <div class="align-right"><a href="#"><span>? list events</span></a></div>
    <span class="clearFix">&nbsp;</span>
  </div>
</div><!-- end of div#calendar-container -->

app/views/user_landing/_date_widget.html.erb
<div id="date-container">
  <img src="<%=asset_path "sunny.png" %>" alt="Sunny"> <span class="hour"><%= Time.now.strftime("%H:%M") %></span> <span class="date">18th May 2009<br>Friday</span>
      <span class="clearFix">&nbsp;</span>
</div>

app/views/user_landing/_header.html.erb
    <div id="header">
      <div id="top">
      <h1><a href="#">Git 'Er Dun!</a></h1>
      <p id="userbox">Hello <strong><%= current_user.first_name %></strong> &nbsp;| &nbsp;<a href="#">Settings</a> &nbsp;| &nbsp; <%= link_to "Logout", destroy_user_session_path, :method => :delete  %> <br />
      <small>Last Login: <%= l current_user.last_sign_in_at, :format => :long %></small></p>
      <span class="clearFix">&nbsp;</span>
      </div>
      <ul id="menu">
        <li <%= "class=selected" if focus == "tasks"%>><%= link_to "Tasks", users_path %></li>
        <li <%= "class=selected" if focus == "quick_timer"%>><%= link_to "Quick Timers", quick_timer_path %></li>
      </ul>
	 <!-- <form action="" method="get" name="form1" id="form1">
      <fieldset>
      <legend>Search</legend>
        <label id="searchbox">
        <input type="text" name="s" id="s" />
        </label>
        <input class="hidden" type="submit" name="Submit" value="Search" />
      </fieldset>
      </form> -->
      <span class="clearFix">&nbsp;</span>
    </div><!-- end of #header -->

app/views/user_landing/_left_column.html.erb
<div id="left-col">
	<div class="box">
		<h4 class="yellow">
			Activities
		</h4>
		<div class="box-container">
			<!-- use no-padding wherever you need element padding gone -->
			<ul class="list-links">
				<li>
					<a href="#">Upcoming Tasks</a>
					<ul>
						<li>
							<%= link_to "List View", users_path(:view => "list", :tasks => "new")%>
						</li>
						<li>
							<%= link_to "Calendar View", users_path(:view => "calendar", :tasks => "new")%>
						</li>
						<li>
							<a href="#">Export</a>
						</li>
					</ul>
				</li>
				<li>
					<a href="#">Finished Tasks</a>
					<ul>
						<li>
							<%= link_to "List View", users_path(:view => "list", :tasks => "old")%>
						</li>
						<li>
							<%= link_to "Calendar View", users_path(:view => "calendar", :tasks => "old")%>
						</li>
						<li>
							<a href="#">Export</a>
						</li>
					</ul>
				</li>
			</ul>
		</div><!--end of div.box-container -->
	</div>
	<div class="box">
		<h4 class="yellow">
			Time
		</h4>
		<div class="box-container">
			<%= render :partial => "user_landing/date_widget" %>
		</div>
	</div>
</div><!-- end of div.box --><!--end of div.box --><!-- end of div.box -->
<!-- end of div#left-col -->

<!-- Maybe refactor this guy, write the JS in-line and have the menu be customized by the templating engine? -->
<%= if params[:tasks]  == "old"
	 javascript_include_tag "old_accordion"
	else
	 javascript_include_tag "new_accordion"
	end
%>

app/views/user_landing/index.html.erb
<% content_for :header do -%>
  <%= stylesheet_link_tag 'user_landing' %>
  <%= javascript_include_tag 'user_landing' %>
<% end %>

<div id="container">
    <div class="hidden">
    <div id="sample-modal"><h2 style="font-size:160%; font-weight:bold; margin:10px 0;">Modal Box Content</h2><p>Place your desired modal box content here</p></div>
    </div><!-- end of hidden -->
    <%= render "header" %>
<div id="content">

      <%= render "left_column" %>
      <%= render "list_view" %>
      
      <span class="clearFix">&nbsp;</span>     

</div><!-- end of div#content -->
<div class="push"></div>
</div><!-- end of #container -->

<div id="footer-wrap">
	<div id="footer">
        <div id="footer-top">
        	<div class="align-left">
            <h4>Dashboard</h4>
            <p><a href="#">Dasboard Sub 1</a> | <a href="#">Dasboard Sub 2</a> | <a href="#">Dasboard Sub 3</a></p>
        	</div>
            <div class="align-right">
            <h2><a href="#">Cleanity</a></h2>
            </div>
            <span class="clearFix"></span>
        </div><!-- end of div#footer-top -->
        
        <div id="footer-bottom">
        	<p>&copy; 2009 Cleanity. Theme by Onur Oztaskiran of <a href="http://www.monofactor.com">Monofactor</a>, 
            via <a href="http://themeforest.net">Themeforest</a></p>
        </div>
        
	</div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_new_list_view.html.erb
    	  <div class="box">
      		<h4 class="white">Upcoming Tasks</h4>
        <div class="box-container">     		
      		<table class="table-long" id="pending-tasks">
      			<thead>
      				<tr>
      					<td>Deadline</td>
      					<td>Description</td>
      					<td></td>
      				</tr>
      			</thead>
      			<tfoot>
      			</tfoot>
            <tbody>
              <% @tasks.each do |t| %>
                <% if not t.completed %>
                <tr class='<%= cycle("odd", "") %><%= " focus" if params[:task_id] == String(t.id) %>'>
                  <td class="col-first"><%= t.deadline %></td>
                  <td class="col-second"><%= link_to (truncate t.description, :length => 50), :view => "list", :tasks => "new", :task_id => t.id  %></td>
                  <td class="row-nav">
                    <%= link_to "Edit", edit_task_path(t), :class => "table-edit-link" %>
                    <span class="hidden"> | </span> 
                    <%= link_to "Delete", t, :class => "table-delete-link", :method => :delete, :confirm => "Are you sure?" %>
                </tr>
                <%end%>
                <%end%>
					<%= link_to "New Task", new_task_path, :class => "table-new-link" %>
      			</tbody>
      		</table>  	
      	</div><!-- end of div.box-container -->
      </div> <!-- end of div.box -->

	<% if @display_task != nil %>
   	<div class="box">
      		<h4 class="white">When?</h4>
        <div class="box-container">     		
      		<table class="table-long">
      			<thead>
      				<tr>
						<td>Created At</td>
      					<td>Deadline</td>
      					<td>Reminder</td>
						<td>Overdue?</td>
      				</tr>
      			</thead>
      			<tfoot>
      			</tfoot>
            <tbody>
				<tr>
					<td class="col-first"><%= @display_task.created_at %></td>
					<td class="col-first"><%= @display_task.deadline %></td>
					<td class="col-first"><%= @display_task.reminder %></td>
					<td class="row-nav"><%= @is_overdue.capitalize %></td>
				</tr>
      			</tbody>
      		</table>  	
      	</div><!-- end of div.box-container -->
      </div> <!-- end of div.box -->
   	<div class="box">
      		<h4 class="white">What?</h4>
        <div class="box-container table-long">     		
      		<%= simple_format @display_task.description %>
      	</div><!-- end of div.box-container -->
      </div> <!-- end of div.box -->
<%end %>

app/views/users/_old_list_view.html.erb
<div class="box">
		<h4 class="white">Completed Tasks</h4>
  <div class="box-container">     		
		<table class="table-long" id="completed-tasks">
			<thead>
				<tr>
					<td>Deadline</td>
					<td>Description</td>
				</tr>
			</thead>
			<tfoot>
			</tfoot>
      	<tbody>
        		<% @tasks.each do |t| %>
          	<% if t.completed %>
          	<tr class='<%= cycle("odd", "") %>'>
            		<td class="col-first"><%= t.deadline %></td>
            		<td class="col-second"><%= t.description %></td>
          	</tr>
          	<%end%>
          	<%end%>
			</tbody>
		</table>  	
	</div><!-- end of div.box-container -->
	</div> <!-- end of div.box -->

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @user.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user.last_name %>
</p>

<p>
  <b>User name:</b>
  <%= @user.user_name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/_splash.html.erb
<div id="text_wrapper">
  <h1> Hello, these are your tasks: </h1>
  <br/>
  <table>
    <tr>
      <th>Task ID</th>
      <th>Description</th>
      <th>Created On</th>
      <th>Deadline</th>
      <th>Completed?</th>
      <th>Reminder</th>
      <th></th>
    </tr>
  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.id =%></td>
      <td><%= task.description =%></td>
      <td><%= task.created_at =%></td>
      <td><%= task.deadline =%></td>
      <td><%= task.completed? =%></td>
      <td><%= task.reminder =%></td>
      <td><%= link_to "Edit Task", "/tasks/#{task.id}/edit" %>
    </tr>
  <% end %>
</table>
</div>

app/views/welcome/old_index.html.erb
<div id='topbar'>
  <div class='left'>
    <h1>GitErDun</h1>
  </div>
    <div class='right'>
      <%if user_signed_in? %>
        Welcome, <%= current_user.first_name %>.
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete  %>
      <% else %>
        Hello! Please <%= link_to "sign in", new_user_session_path %> or <%= link_to "create an account", new_user_registration_path %>.
      <% end %>
   </div>
</div>

<div id='bottombar'>
      <%if not user_signed_in? %>
          <%= render :partial => "bottom" %>
        <% else%>
          <%= render :partial => "splash" %>          
      <% end %>
</div>